(ns render-pipelines
  "Render every pipeline in the export registry as a nested-list view
   and write them out to /work/dev/data/pipelines.md.

   Run (the JVM `--add-opens` flags are needed for lmdb-using
   pipelines on JDK 16+):

     clojure -J--add-opens=java.base/java.nio=ALL-UNNAMED \\
             -J--add-opens=java.base/sun.nio.ch=ALL-UNNAMED \\
             -M -e '(load-file \"/work/dev/render_pipelines.clj\")'

   To override the output path, call `-main` explicitly:

     clojure -J... -M -e '(load-file \"/work/dev/render_pipelines.clj\")
                          (render-pipelines/-main \"/tmp/foo.md\")'"
  (:require [clojure.java.io :as io]
            [clojure.string :as str]
            [datapotamus-export :as export]
            [toolkit.datapotamus.render :as render]))

(defn- ns-docstring [ns-sym]
  (some-> (find-ns ns-sym) meta :doc str/trim not-empty))

(defn- build-stepmap [{:keys [ns invoke]}]
  (require ns)
  (let [v (some-> (ns-resolve ns 'build-flow) deref)]
    (when-not v
      (throw (ex-info (str ns "/build-flow not found") {:ns ns})))
    (case invoke
      :no-args   (v)
      :opts-map  (try (v) (catch clojure.lang.ArityException _ (v {})))
      :usernames (v ["dang"]))))

(defn- entry->markdown [{:keys [ns] :as spec}]
  (let [header (str "## " ns)]
    (try
      (let [sm     (build-stepmap spec)
            lines  (render/render sm)
            doc    (ns-docstring ns)
            body   (if (seq lines)
                     (str "```\n" (str/join "\n" lines) "\n```")
                     "_(empty pipeline)_")]
        (str header "\n\n"
             (when doc (str "> " (str/replace doc #"\n" "\n> ") "\n\n"))
             body))
      (catch Throwable t
        (str header "\n\n_(error: " (.getMessage t) ")_")))))

(defn -main [& [out]]
  (let [out-path (or out "/work/dev/data/pipelines.md")
        sections (mapv entry->markdown export/pipelines)
        doc      (str "# Datapotamus pipelines — rendered\n\n"
                      "_Auto-generated by `dev/render_pipelines.clj`._\n\n"
                      "Indented nested-list view of every pipeline in the export\n"
                      "registry. `↩ <name>` marks an off-spine edge — for `:cycle`\n"
                      "shapes it's a feedback loop; for `:prime` shapes it's a\n"
                      "forward edge that skips spine positions.\n\n"
                      (str/join "\n\n" sections)
                      "\n")]
    (io/make-parents out-path)
    (spit out-path doc)
    (println (format "Wrote %d pipelines → %s" (count export/pipelines) out-path))))

(apply -main *command-line-args*)
