(ns render-random-sp
  "Generate random SP-DAGs and render them. Used to visually inspect
   the rendered structure of decomposed SP shapes — a kind of
   manually-driven property test where a human (you) checks that
   the rendering follows the rules in `kb/pipeline-diagrams.md`.

   Run:
     clojure -M -e '(load-file \"/work/dev/render_random_sp.clj\")'

   Writes `/work/dev/data/random_sp_renders.md`."
  (:require [clojure.java.io :as io]
            [clojure.set :as set]
            [clojure.string :as str]
            [clojure.test.check.generators :as gen]
            [clojure.test.check.random :as random]
            [clojure.test.check.rose-tree :as rose]
            [toolkit.datapotamus.render :as render]
            [toolkit.datapotamus.shape :as shape]))

;; --- Same generators as in shape_test.clj --------------------------------

(def gen-sp-tree
  (gen/recursive-gen
   (fn [g]
     (gen/one-of
      [(gen/let [n (gen/choose 2 4)
                 children (gen/vector g n)]
         [:series children])
       (gen/let [n (gen/choose 2 3)
                 children (gen/vector g n)]
         [:parallel children])]))
   (gen/return :leaf)))

(defn- materialize-sp [tree src snk fresh-id]
  (cond
    (= tree :leaf)
    {:nodes #{src snk} :edges #{[src snk]}}

    (= :series (first tree))
    (let [children (second tree)
          n (count children)
          intermediates (vec (repeatedly (dec n) fresh-id))
          endpoints (vec (concat [src] intermediates [snk]))
          subs (mapv #(materialize-sp %1 %2 %3 fresh-id)
                     children
                     (butlast endpoints)
                     (rest endpoints))]
      {:nodes (reduce set/union #{} (map :nodes subs))
       :edges (reduce set/union #{} (map :edges subs))})

    (= :parallel (first tree))
    (let [children (second tree)
          ;; Each leaf in parallel needs its own intermediate node so
          ;; multiple atomic edges between src and snk don't collapse
          ;; to a single edge in our simple-graph representation.
          subs (mapv (fn [child]
                       (if (= child :leaf)
                         (let [m (fresh-id)]
                           {:nodes #{src m snk}
                            :edges #{[src m] [m snk]}})
                         (materialize-sp child src snk fresh-id)))
                     children)]
      {:nodes (reduce set/union #{} (map :nodes subs))
       :edges (reduce set/union #{} (map :edges subs))})))

(defn- sp-tree->topology [tree]
  (let [counter (atom 0)
        fresh-id #(let [id (swap! counter inc)]
                    [(keyword (str "n" id))])
        src (fresh-id)
        snk (fresh-id)
        graph (materialize-sp tree src snk fresh-id)]
    {:nodes (mapv (fn [path] {:path path :kind :leaf :name (name (last path))})
                  (sort (:nodes graph)))
     :edges (mapv (fn [[u v]] {:from-path u :to-path v})
                  (:edges graph))}))

;; --- Sampling generator at a fixed size ----------------------------------

(defn- sample-tree [size seed-int]
  (let [rng (random/make-random seed-int)
        rose (gen/call-gen gen-sp-tree rng size)]
    (rose/root rose)))

;; --- Markdown writer -----------------------------------------------------

(defn- describe-sp-tree
  "Pretty-print an SP-tree as a one-line summary."
  [tree]
  (cond
    (= tree :leaf) "·"
    (= :series (first tree))
    (str "(" (str/join " ; " (map describe-sp-tree (second tree))) ")")
    (= :parallel (first tree))
    (str "(" (str/join " | " (map describe-sp-tree (second tree))) ")")))

(defn- render-one [tree size seed]
  (let [topology (sp-tree->topology tree)
        n-nodes  (count (:nodes topology))
        n-edges  (count (:edges topology))
        lines    (try (render/render topology)
                      (catch Throwable t [(str "ERROR: " (.getMessage t))]))]
    (str "## seed " seed " — size " size " — " n-nodes " nodes / " n-edges " edges\n\n"
         "**SP-algebra:** `" (describe-sp-tree tree) "`\n\n"
         "**Render:**\n\n"
         "```\n" (str/join "\n" lines) "\n```\n\n")))

(defn -main
  ([] (-main "/work/dev/data/random_sp_renders.md"))
  ([out-path]
   (let [seeds (range 1 31)
         sizes [5 10 15]
         entries (for [size sizes
                       seed seeds]
                   (let [tree (sample-tree size seed)]
                     (render-one tree size seed)))
         doc (str "# Random SP-DAG renders\n\n"
                  "_Auto-generated by `dev/render_random_sp.clj`._\n\n"
                  "Generated SP-trees by recursive composition; materialized to\n"
                  "topology; rendered. For visual inspection of the rendering\n"
                  "rules from `kb/pipeline-diagrams.md`.\n\n"
                  "Notation: `·` = leaf (single edge), `;` = series, `|` =\n"
                  "parallel.\n\n"
                  (str/join "" entries))]
     (io/make-parents out-path)
     (spit out-path doc)
     (println (format "Wrote %s" out-path)))))

(-main)
