(ns toolkit.datapotamus
  "Datapotamus: a thin layer over clojure.core.async.flow that adds a
   scope-prefixed pubsub for trace emission and a ledger-based message
   algebra for composable token accounting.

   The unit of composition is a **step**: a map of the shape

     {:procs  {sid factory, ...}   ; factory is (fn [ctx] step-fn)
      :conns  [[[from-sid from-port] [to-sid to-port]], ...]
      :in  sid-or-[sid port]       ; required for run!
      :out sid-or-[sid port]}      ; boundary for outer composition

   A step with one proc is still a step; `serial`, `merge-steps`, and
   `as-step` all produce steps.

   Factories are 1-arg fns that take a ctx and return a 4-arity
   core.async.flow process-fn. ctx carries:

     :pubsub   — ScopedPubsub prefixed with this step's scope
     :step-id  — this step's id, as it appears in trace events
     :cancel   — promise, delivered on stop!; poll with `realized?`

   At message time the ctx is further extended with

     :in-port  — the port this invocation arrived on
     :msg      — the current input message envelope
     :ledger   — per-invocation derivation atom; consumed by the
                 message-construction helpers (`child`, `children`,
                 `pass`, `signal`, `merge`)

   Handlers return `[s' [[port msg-or-data] ...]]` — a new state plus
   a seq of port/value pairs. Handler signature is `(fn [ctx s d])`
   where `d` is the input data (shorthand for `(:data (:msg ctx))`).
   A `value` in the outputs that is a message built via one of the
   helpers is routed as-is; a bare value is sugar for
   `(child ctx value)` and is coerced by the wrapper before synthesis.

   ## Token conservation

   Tokens live in an abelian group under XOR. Three invariants compose:

     (1) 1-to-1 preserves tokens.
         (child p d).tokens = p.tokens

     (2) N-way split preserves XOR sum.
         XOR over (children p [d_1..d_N]).tokens = p.tokens

     (3) Merge combines tokens.
         (merge [p_1..p_N] d).tokens = XOR over p_i.tokens

   Fan-out introduces a fresh zero-sum group: N children tagged with
   values XOR-summing to 0. Fan-in closes the group when it sees
   arrivals whose XOR-sum returns to 0 — emitting a merge msg and
   stripping the closed group's key. Because (1)(2)(3) compose, any
   chain of steps preserves every upstream group's XOR sum; downstream
   fan-ins fire exactly when their groups actually close.

   Users who stay within the helpers (`child`/`children`/`pass`/
   `signal`/`merge`) get these invariants by construction. Hand-built
   messages that stamp `::extra-tokens` metadata (e.g. inside custom
   combinators) are the one place where the invariant becomes a manual
   obligation — the combinator is responsible for XOR-summing its
   stamped values to 0 across siblings.

   ## Trace events

   The event stream is orthogonal on two axes:

     :kind       — lifecycle role (:recv :success :failure :send-out
                   :split :merge :seed :run-started)
     :msg-kind   — message type (:data :signal :done) when applicable

   This means `:kind :recv :msg-kind :signal` replaces what was a
   separate `:recv-signal` event, and so on. Subjects are built from
   `:kind` only — consumers who care about `:msg-kind` filter in the
   handler.

   File layout (narrative order, top to bottom):

     Part 1 — Messages      envelope, ledger, helpers, fcatch
     Part 2 — Tracing       events, counters, scope+pubsub
     Part 3 — Synthesis     token synthesis, event emission for ledger
     Part 4 — Steps         step/proc + single-step blueprints
     Part 5 — Composition   serial, merge-steps, connect, input-at, output-at
     Part 6 — Combinators   fan-out, fan-in, router, retry
     Part 7 — wrap-proc     the step-execution wrapper
     Part 8 — Flow lifecycle  instrument, start!, inject!, stop!, run!, run-seq"
  (:refer-clojure :exclude [merge run!])
  (:require [clojure.core.async :as a]
            [clojure.core.async.flow :as flow]
            [clojure.set :as set]
            [clojure.string :as str]
            [toolkit.datapotamus.token :as tok]
            [toolkit.pubsub :as pubsub]))

(set! *warn-on-reflection* true)

;; ============================================================================
;; Part 1 — Messages
;;
;; Three structural message kinds distinguished by key absence:
;;   data:   has :data,  has :tokens
;;   signal: no  :data,  has :tokens
;;   done:   no  :data,  no  :tokens
;;
;; Done messages are port-closure markers generated by the wrapper when
;; all declared input ports have closed. They bypass the user handler
;; and the ledger entirely.
;;
;; Data and signal messages go through the ledger — every construction
;; inside a handler is recorded there, and the wrapper walks the
;; derivation DAG at the end to assign tokens. `::pending` is the
;; placeholder tokens field on provisional messages returned from the
;; helpers; real tokens are stamped on by the wrapper before emission.
;; ============================================================================

(defn new-msg
  "Root msg: no parent. Starts with empty tokens."
  [data]
  {:msg-id (random-uuid) :data-id (random-uuid) :data data
   :tokens {} :parent-msg-ids []})

(defn signal?
  "True iff `m` is a signal message — carries tokens and lineage but no
   payload. Identified by absence of the `:data` key (not a sentinel
   value), so `nil` is a legitimate data value."
  [m]
  (not (contains? m :data)))

(defn done?
  "True iff `m` is a done message — a port-closure marker. No `:data`,
   no `:tokens`."
  [m]
  (and (not (contains? m :data))
       (not (contains? m :tokens))))

(defn new-done
  "Fresh port-closure marker."
  []
  {:msg-id (random-uuid) :at (System/currentTimeMillis)})

;; --- ledger ------------------------------------------------------------------
;;
;; One ledger atom per handler invocation, stored under ctx's `:ledger`
;; key. Nodes are keyed by msg-id; :order preserves registration order
;; (which is topological because helpers register after their parents).
;;
;; Node shape:
;;   {:op :split :parent <id> :data <d> :data-id <uuid>}           data child
;;   {:op :split :parent <id> :data-id <uuid>}                     signal child (no :data key)
;;   {:op :split :parent <id> :data <d> :data-id <uuid>            `pass` result
;;    :preserve-data-id? true}
;;   {:op :merge :parents [<id>...] :data <d> :data-id <uuid>
;;    :external-tokens <map>}                                       multi-parent

(defn- new-ledger [input-msg]
  (atom {:root (:msg-id input-msg)
         :root-tokens (:tokens input-msg {})
         :order []
         :nodes {}}))

(defn- register-split! [ledger parent-id msg preserve-data-id?]
  (let [node (cond-> {:op :split :parent parent-id :data-id (:data-id msg)}
               (contains? msg :data) (assoc :data (:data msg))
               preserve-data-id?     (assoc :preserve-data-id? true))]
    (swap! ledger #(-> %
                       (update :order conj (:msg-id msg))
                       (assoc-in [:nodes (:msg-id msg)] node)))))

(defn- register-merge! [ledger parent-ids external-tokens msg]
  (let [node {:op :merge :parents (vec parent-ids)
              :external-tokens external-tokens
              :data (:data msg) :data-id (:data-id msg)}]
    (swap! ledger #(-> %
                       (update :order conj (:msg-id msg))
                       (assoc-in [:nodes (:msg-id msg)] node)))))

;; --- public helpers ---------------------------------------------------------

(defn child
  "Single-parent derive. 2-arity uses `(:msg ctx)` as parent; 3-arity
   takes an explicit parent. Returns a provisional message carrying
   `::pending` tokens; the wrapper stamps final tokens after the
   handler returns."
  ([ctx data] (child ctx (:msg ctx) data))
  ([ctx parent data]
   (let [msg {:msg-id (random-uuid)
              :data-id (random-uuid)
              :data data
              :tokens ::pending
              :parent-msg-ids [(:msg-id parent)]}]
     (register-split! (:ledger ctx) (:msg-id parent) msg false)
     msg)))

(defn children
  "N-way derive of `(:msg ctx)` (or the explicit `parent`)."
  ([ctx datas] (children ctx (:msg ctx) datas))
  ([ctx parent datas]
   (mapv #(child ctx parent %) datas)))

(defn pass
  "Same data as `(:msg ctx)`, preserves its `:data-id`. Use when a
   step routes or coordinates without transforming the payload."
  [ctx]
  (let [parent (:msg ctx)
        msg {:msg-id (random-uuid)
             :data-id (:data-id parent)
             :data (:data parent)
             :tokens ::pending
             :parent-msg-ids [(:msg-id parent)]}]
    (register-split! (:ledger ctx) (:msg-id parent) msg true)
    msg))

(defn signal
  "Signal child of `(:msg ctx)` — carries tokens and lineage but no
   payload. Downstream steps' user handlers are not invoked on signal
   messages; they are used for per-group coordination."
  [ctx]
  (let [parent (:msg ctx)
        msg {:msg-id (random-uuid)
             :data-id (random-uuid)
             :tokens ::pending
             :parent-msg-ids [(:msg-id parent)]}]
    (register-split! (:ledger ctx) (:msg-id parent) msg false)
    msg))

(defn merge
  "Multi-parent derive. XOR-combines parent tokens; publishes a `:merge`
   trace event. External parents' tokens are captured at call time;
   internal (ledger-built) parents contribute via the DAG walk."
  [ctx parents data]
  (let [ledger     (:ledger ctx)
        root-id    (:root @ledger)
        parent-ids (mapv :msg-id parents)
        external-tokens
        (reduce (fn [acc p]
                  (cond
                    (= (:msg-id p) root-id) acc
                    (= ::pending (:tokens p)) acc
                    :else (tok/merge-tokens acc (:tokens p {}))))
                {} parents)
        msg {:msg-id (random-uuid)
             :data-id (random-uuid)
             :data data
             :tokens ::pending
             :parent-msg-ids parent-ids}]
    (register-merge! ledger parent-ids external-tokens msg)
    msg))

(defn- ledger-msg?
  "True iff `x` is a provisional message returned by one of the helpers."
  [x]
  (and (map? x) (= ::pending (:tokens x))))

;; --- fcatch -----------------------------------------------------------------

(defn fcatch
  "Wrap `f` so it returns exceptions rather than throwing them."
  [f]
  (fn [& args]
    (try (apply f args)
         (catch Throwable t t))))

;; ============================================================================
;; Part 2 — Tracing (events, counters, scoped pubsub)
;;
;; :kind is the lifecycle role; :msg-kind is the message type where
;; applicable. This gives a 4×3 grid for message lifecycle events
;; (:recv/:success/:send-out/:failure × :data/:signal/:done, minus
;; :failure on non-data) plus :split / :merge for ledger derivations
;; and :seed / :run-started for run-level events.
;; ============================================================================

(defn- now [] (System/currentTimeMillis))

;; --- event constructors (internal) ------------------------------------------

(defn- recv-event
  "Build a :recv event for any msg-kind. For :done, pass `in-port`."
  ([step-id msg-kind m] (recv-event step-id msg-kind m nil))
  ([step-id msg-kind m in-port]
   (cond-> {:kind :recv :msg-kind msg-kind :step-id step-id
            :msg-id (:msg-id m) :at (now)}
     (= :data msg-kind)   (assoc :data-id (:data-id m) :data (:data m))
     (= :signal msg-kind) (assoc :data-id (:data-id m) :tokens (:tokens m))
     (= :done msg-kind)   (assoc :in-port in-port))))

(defn- success-event [step-id msg-kind m]
  {:kind :success :msg-kind msg-kind :step-id step-id
   :msg-id (:msg-id m) :at (now)})

(defn- failure-event [step-id m ^Throwable ex]
  {:kind :failure :msg-kind :data :step-id step-id :msg-id (:msg-id m)
   :error {:message (ex-message ex) :data (ex-data ex)} :at (now)})

(defn- send-out-event [step-id msg-kind port child]
  (cond-> {:kind :send-out :msg-kind msg-kind :port port :step-id step-id
           :msg-id (:msg-id child) :at (now)}
    (not= :done msg-kind)
    (assoc :data-id (:data-id child)
           :parent-msg-ids (vec (:parent-msg-ids child))
           :tokens (:tokens child))

    (= :data msg-kind)
    (assoc :data (:data child))))

(defn- split-event [step-id child]
  {:kind :split :step-id step-id
   :msg-id (:msg-id child) :data-id (:data-id child)
   :parent-msg-ids (vec (:parent-msg-ids child))
   :tokens (:tokens child) :data (:data child) :at (now)})

(defn- merge-event [step-id msg-id parents]
  {:kind :merge :step-id step-id :msg-id msg-id
   :parent-msg-ids (vec parents) :at (now)})

;; --- counter logic ----------------------------------------------------------

(defn- update-counters [counters ev]
  (case (:kind ev)
    :recv     (update counters :recv inc)
    :success  (update counters :completed inc)
    :failure  (update counters :completed inc)
    :send-out (if (:port ev) (update counters :sent inc) counters)
    counters))

(defn- balanced?
  "True iff counters indicate all work so far has resolved."
  [{:keys [sent recv completed]}]
  (and (pos? sent) (= sent recv) (= recv completed)))

;; --- scope + subject --------------------------------------------------------

(defn- scope->segments [scope]
  (mapcat (fn [[k id]]
            [(name k) (if (keyword? id) (name id) (str id))])
          scope))

(defn- subject-for [scope kind]
  (->> (cons (name kind) (scope->segments scope))
       (str/join ".")))

(defn- run-subject-for [scope kind]
  (->> (cons (name kind) (concat (scope->segments scope) ["run"]))
       (str/join ".")))

(defn- flow-path-of [scope]
  (mapv (fn [[_ id]] (if (keyword? id) (name id) id))
        (filter (fn [[k _]] (= k :flow)) scope)))

(defn- scope->glob [scope]
  (str "*." (str/join "." (scope->segments scope)) ".>"))

;; --- scoped pubsub ----------------------------------------------------------

(defrecord ScopedPubsub [raw prefix])

(defn- scoped-pubsub [raw prefix]
  (->ScopedPubsub raw (vec prefix)))

(defn- sp-pub [^ScopedPubsub sp ev]
  (let [prefix (.prefix sp)]
    (pubsub/pub (.raw sp)
                (subject-for prefix (:kind ev))
                (assoc ev :scope prefix :flow-path (flow-path-of prefix)))))

(defn- sp-extend [^ScopedPubsub sp segment]
  (->ScopedPubsub (.raw sp) (conj (.prefix sp) segment)))

;; ============================================================================
;; Part 3 — Synthesis
;;
;; After a handler returns:
;;   1. Coerce bare data outputs to registered children (in the ledger).
;;   2. Build the DAG: {parent-id [child-id ...]}.
;;   3. Seed token map: root gets root-tokens; every :merge node gets
;;      its captured external-tokens.
;;   4. Distribute: walk (cons root order) in topological order; for
;;      each parent with K resolvable children, split its tokens
;;      K-ways; :split kids assign, :merge kids XOR-merge.
;;   5. Materialize each ledger node as a final message.
;;   6. Publish :split / :merge events in registration order.
;; ============================================================================

(defn- children-by-parent
  "Reverse-adjacency: {parent-id [child-id ...]} in registration order.
   Skips parents not resolvable in the ledger (external merge parents)."
  [nodes order resolvable?]
  (reduce
   (fn [acc id]
     (let [node (get nodes id)]
       (case (:op node)
         :split (cond-> acc
                  (resolvable? (:parent node))
                  (update (:parent node) (fnil conj []) id))
         :merge (reduce (fn [a p]
                          (cond-> a (resolvable? p) (update p (fnil conj []) id)))
                        acc (:parents node)))))
   {} order))

(defn- seed-tokens
  "Initial tokens map: root plus external-tokens for every :merge node."
  [root root-tokens nodes order]
  (reduce (fn [acc id]
            (let [node (get nodes id)]
              (cond-> acc
                (= :merge (:op node))
                (assoc id (or (:external-tokens node) {})))))
          {root root-tokens}
          order))

(defn- distribute-tokens
  "Walk parents in topological order; split each parent's tokens K-ways
   across its resolvable children and contribute to each child's entry."
  [tokens nodes children-idx walk-order]
  (reduce
   (fn [tokens parent-id]
     (let [kids (get children-idx parent-id)]
       (if (empty? kids)
         tokens
         (let [splits (tok/split-tokens (get tokens parent-id {}) (count kids))]
           (reduce (fn [t [kid-id slice]]
                     (case (:op (get nodes kid-id))
                       :split (assoc t kid-id slice)
                       :merge (update t kid-id #(tok/merge-tokens (or % {}) slice))))
                   tokens
                   (map vector kids splits))))))
   tokens
   walk-order))

(defn- synthesize-tokens
  "Return {msg-id tokens} for every node in the ledger snapshot."
  [{:keys [root root-tokens order nodes]}]
  (let [resolvable?  #(or (= % root) (contains? nodes %))
        children-idx (children-by-parent nodes order resolvable?)
        initial      (seed-tokens root root-tokens nodes order)]
    (distribute-tokens initial nodes children-idx (cons root order))))

(defn- materialize-msg
  "Build the final message for a ledger node, applying ::extra-tokens /
   ::drop-tokens metadata stamped by combinators (fan-out / fan-in)."
  [id node tokens extra-tokens drop-tokens]
  (let [tokens'  (tok/merge-tokens tokens (or extra-tokens {}))
        tokens'' (if (seq drop-tokens)
                   (apply dissoc tokens' drop-tokens)
                   tokens')
        base     {:msg-id id
                  :data-id (:data-id node)
                  :tokens tokens''
                  :parent-msg-ids (case (:op node)
                                    :split [(:parent node)]
                                    :merge (:parents node))}]
    (cond-> base
      (contains? node :data) (assoc :data (:data node)))))

(defn- coerce-bare-outputs!
  "Replace bare-data values in `raw-outputs` with registered provisional
   messages; leave ledger-built messages as-is."
  [ctx raw-outputs]
  (mapv (fn [[port v]]
          (if (ledger-msg? v)
            [port v]
            [port (child ctx v)]))
        raw-outputs))

(defn- process-ledger!
  "Drive the post-handler pipeline. Returns `{port [final-msg ...]}`
   and publishes :split / :merge events in registration order."
  [ctx raw-outputs]
  (let [outputs'   (coerce-bare-outputs! ctx (or raw-outputs []))
        meta-by-id (reduce (fn [acc [_ prov]]
                             (let [mm (meta prov)]
                               (if (or (::extra-tokens mm) (::drop-tokens mm))
                                 (assoc acc (:msg-id prov) mm)
                                 acc)))
                           {} outputs')
        snap       @(:ledger ctx)
        tokens-by  (synthesize-tokens snap)
        nodes      (:nodes snap)
        final-by-id (reduce-kv
                     (fn [acc id node]
                       (let [mm (get meta-by-id id)]
                         (assoc acc id
                                (materialize-msg id node
                                                 (get tokens-by id {})
                                                 (::extra-tokens mm)
                                                 (::drop-tokens mm)))))
                     {} nodes)
        step-id    (:step-id ctx)
        step-sp    (:pubsub ctx)]
    (doseq [id (:order snap)
            :let [node (get nodes id)
                  msg  (get final-by-id id)]]
      (case (:op node)
        :split (sp-pub step-sp (split-event step-id msg))
        :merge (sp-pub step-sp (merge-event step-id id (:parent-msg-ids msg)))))
    (reduce (fn [acc [port prov]]
              (let [final (get final-by-id (:msg-id prov))]
                (update acc port (fnil conj []) final)))
            {} outputs')))

;; ============================================================================
;; Part 4 — Steps
;; ============================================================================

(def ^:private auto-id-counters (atom {}))

(defn- gen-id [kind]
  (let [n (-> (swap! auto-id-counters update kind (fnil inc 0)) (get kind))]
    (keyword (str (name kind) "-" n))))

(defn- handler-factory
  "Lift a 3-arg message handler `(fn [ctx s d] -> [s' outputs])` into a
   full factory `(fn [ctx] step-fn)` that satisfies core.async.flow's
   4-arity proc-fn shape.

   `d` is the input data (shorthand for `(:data (:msg ctx))`). The
   full envelope is on `(:msg ctx)` if needed (tokens, lineage, etc.).

   `outputs` is a seq of `[port msg-or-data]` pairs. A ledger is
   created per 4-arity invocation and attached to ctx; bare data in
   outputs is coerced via `child` during synthesis."
  ([handler] (handler-factory nil handler))
  ([ports handler]
   (let [ins  (:ins  ports {:in  ""})
         outs (:outs ports {:out ""})]
     (fn [factory-ctx]
       (fn ([]             {:params {} :ins ins :outs outs})
         ([_]            {})
         ([s _]          s)
         ([s in-port m]
          (let [ledger   (new-ledger m)
                ctx      (assoc factory-ctx :in-port in-port :msg m :ledger ledger)
                [s' raw] (handler ctx s (:data m))]
            [s' (process-ledger! ctx raw)])))))))

(defn- pure-fn-handler
  "Lift a pure (data -> data) fn: emits (f d) as bare data on :out."
  [f]
  (fn [_ctx s d]
    [s [[:out (f d)]]]))

(defn proc
  "Low-level: wrap a raw core.async.flow factory `(fn [ctx] step-fn)`
   into a 1-proc step. Most users want `step` instead."
  [id factory]
  {:procs {id factory} :conns [] :in id :out id})

(defn step
  "Build a 1-proc step.

   2-arity — pure-fn form:
     (step id f)        ; f is (data -> data), ports default to :in / :out

   3-arity — handler form:
     (step id ports handler)
       ports   = {:ins {port-kw \"\"} :outs {port-kw \"\"}}
       handler = (fn [ctx s d] -> [s' [[port msg-or-data] ...]])

   `d` is the incoming data (the `:data` field of the input message).
   Full envelope is on `(:msg ctx)`."
  ([id f]
   (proc id (handler-factory (pure-fn-handler f))))
  ([id ports handler]
   (proc id (handler-factory ports handler))))

(defn sink
  "Terminal step — consumes input, emits nothing."
  ([] (sink :sink))
  ([id]
   (proc id (handler-factory {:outs {}} (fn [_ctx s _d] [s []])))))

(defn passthrough
  "Identity step: forwards data unchanged with preserved data-id."
  ([] (passthrough (gen-id :passthrough)))
  ([id]
   (proc id (handler-factory (fn [ctx s _d] [s [[:out (pass ctx)]]])))))

(defn as-step
  "Black-box `inner-step` as a single proc under `id`."
  [id inner-step]
  {:procs {id inner-step} :conns [] :in id :out id})

;; ============================================================================
;; Part 5 — Composition
;; ============================================================================

(defn- assert-no-collision! [a b context]
  (let [coll (set/intersection (set (keys (:procs a))) (set (keys (:procs b))))]
    (when (seq coll)
      (throw (ex-info (str context ": colliding proc ids") {:colliding coll})))))

(defn- ref->endpoint [ref default-port]
  (if (vector? ref) ref [ref default-port]))

(defn- conn-glue [from-step to-step]
  [(ref->endpoint (:out from-step) :out)
   (ref->endpoint (:in to-step) :in)])

(defn serial
  "Compose steps sequentially."
  [& steps]
  (when (empty? steps)
    (throw (ex-info "serial needs at least one step" {})))
  (reduce (fn [acc f]
            (assert-no-collision! acc f "serial")
            {:procs  (clojure.core/merge (:procs acc) (:procs f))
             :conns  (conj (into (vec (:conns acc)) (:conns f))
                           (conn-glue acc f))
             :in  (:in acc)
             :out (:out f)})
          (first steps)
          (rest steps)))

(defn merge-steps
  "Union procs and conns without auto-wiring."
  [& steps]
  (when (empty? steps)
    (throw (ex-info "merge-steps needs at least one step" {})))
  (reduce (fn [acc f]
            (assert-no-collision! acc f "merge-steps")
            (-> acc
                (update :procs clojure.core/merge (:procs f))
                (update :conns (fnil into []) (:conns f))))
          (first steps)
          (rest steps)))

(defn connect
  "Add an explicit conn."
  [step from to]
  (update step :conns (fnil conj [])
          [(ref->endpoint from :out) (ref->endpoint to :in)]))

(defn input-at
  "Set the step's :in boundary."
  [step ref]
  (assoc step :in ref))

(defn output-at
  "Set the step's :out boundary."
  [step ref]
  (assoc step :out ref))

;; ============================================================================
;; Part 6 — Combinators
;; ============================================================================

(defn fan-out
  "Emit N copies of the input on :out with a fresh zero-sum token group."
  ([group-id n] (fan-out group-id group-id n))
  ([id group-id n]
   (proc id
         (handler-factory
          (fn [ctx s d]
            (let [gid    [group-id (:msg-id (:msg ctx))]
                  values (tok/split-value 0 n)
                  kids   (children ctx (repeat n d))
                  kids'  (mapv (fn [k v]
                                 (vary-meta k assoc ::extra-tokens {gid v}))
                               kids values)]
              [s (mapv (fn [k] [:out k]) kids')]))))))

(defn fan-in
  "Accumulate inputs grouped by token-ids produced by `fan-out`."
  ([group-id] (fan-in group-id group-id))
  ([id group-id]
   (proc id
         (handler-factory
          (fn [ctx s _d]
            (let [m    (:msg ctx)
                  gids (filterv (fn [k] (and (vector? k) (= group-id (first k))))
                                (keys (:tokens m)))]
              (reduce
               (fn [[s' output] gid]
                 (let [v    (long (get (:tokens m) gid))
                       grp  (get-in s' [:groups gid] {:value 0 :msgs []})
                       grp' (-> grp
                                (update :value (fn [x] (bit-xor (long x) v)))
                                (update :msgs conj m))]
                   (if (zero? (long (:value grp')))
                     (let [merged (-> (merge ctx (:msgs grp') (mapv :data (:msgs grp')))
                                      (vary-meta assoc ::drop-tokens #{gid}))]
                       [(update s' :groups dissoc gid)
                        (conj output [:out merged])])
                     [(assoc-in s' [:groups gid] grp') output])))
               [s []]
               gids)))))))

(defn router
  "Route input to multiple ports based on `(route-fn data)`."
  [id ports route-fn]
  (let [port-set (set ports)]
    (proc id
          (handler-factory
           {:outs (zipmap ports (repeat ""))}
           (fn [ctx s d]
             (let [routes (vec (route-fn d))]
               (doseq [{:keys [port]} routes]
                 (when-not (port-set port)
                   (throw (IllegalArgumentException.
                           (str "router: unknown port " port)))))
               (let [kids (children ctx (mapv :data routes))]
                 [s (mapv (fn [route kid] [(:port route) kid])
                          routes kids)])))))))

(defn retry
  "Wrap a (data -> data) fn. Retries on exception up to `max-attempts`."
  [id f max-attempts]
  (proc id
        (handler-factory
         (fn [_ctx s d]
           (loop [attempt 1]
             (let [result (try {:ok (f d)}
                               (catch Throwable t {:err t}))]
               (if (contains? result :ok)
                 [s [[:out (:ok result)]]]
                 (if (< attempt max-attempts)
                   (recur (inc attempt))
                   (throw (:err result))))))))))

;; ============================================================================
;; Part 7 — wrap-proc
;; ============================================================================

(defn- wrap-proc [trace-sid step-sp user-step-fn]
  (let [ports         (user-step-fn)
        ins           (:ins ports)
        outs          (:outs ports)
        all-in-ports  (set (keys ins))
        declared-outs (set (keys outs))
        done-ins      (atom #{})]
    (fn
      ([] (user-step-fn))
      ([arg] (user-step-fn arg))
      ([s arg] (user-step-fn s arg))
      ([s in-id m]
       (cond
         (done? m)
         (let [closed-ins (swap! done-ins conj in-id)]
           (sp-pub step-sp (recv-event trace-sid :done m in-id))
           (if (= closed-ins all-in-ports)
             (let [forwards (into {} (map (fn [p] [p [(new-done)]])) (keys outs))]
               (doseq [[p [d]] forwards]
                 (sp-pub step-sp (send-out-event trace-sid :done p d)))
               (sp-pub step-sp (success-event trace-sid :done m))
               [s forwards])
             (do
               (sp-pub step-sp (success-event trace-sid :done m))
               [s {}])))

         (signal? m)
         (let [_         (sp-pub step-sp (recv-event trace-sid :signal m))
               out-ports (vec (keys outs))
               n         (count out-ports)]
           (if (pos? n)
             (let [splits   (tok/split-tokens (:tokens m {}) n)
                   kids     (mapv (fn [slice]
                                    {:msg-id (random-uuid)
                                     :data-id (random-uuid)
                                     :tokens slice
                                     :parent-msg-ids [(:msg-id m)]})
                                  splits)
                   forwards (zipmap out-ports (map vector kids))]
               (doseq [[p [sig]] forwards]
                 (sp-pub step-sp (send-out-event trace-sid :signal p sig)))
               (sp-pub step-sp (success-event trace-sid :signal m))
               [s forwards])
             (do
               (sp-pub step-sp (success-event trace-sid :signal m))
               [s {}])))

         :else
         (do
           (sp-pub step-sp (recv-event trace-sid :data m))
           (try
             (let [[s' port-map] (user-step-fn s in-id m)
                   user-ports    (set (keys port-map))
                   unknown-ports (set/difference user-ports declared-outs)
                   _             (when (seq unknown-ports)
                                   (throw (ex-info
                                           (str "step " trace-sid
                                                " emitted on undeclared port(s): "
                                                unknown-ports
                                                " (declared: " declared-outs ")")
                                           {:step           trace-sid
                                            :unknown-ports  unknown-ports
                                            :declared-ports declared-outs})))]
               (doseq [[port msgs] port-map
                       msg msgs]
                 (sp-pub step-sp (send-out-event trace-sid :data port msg)))
               (sp-pub step-sp (success-event trace-sid :data m))
               [s' port-map])
             (catch Throwable ex
               (sp-pub step-sp (failure-event trace-sid m ex))
               [s {}]))))))))

;; ============================================================================
;; Part 8 — Flow lifecycle
;; ============================================================================

(defn- subflow? [v]
  (and (map? v) (contains? v :procs) (contains? v :conns)))

(defn- prefix-sid [prefix sid]
  (keyword (str (name prefix) "." (name sid))))

(defn- prefix-endpoint [prefix [sid port]]
  [(prefix-sid prefix sid) port])

(defn- prefix-ref [prefix ref]
  (if (vector? ref)
    [(prefix-sid prefix (first ref)) (second ref)]
    (prefix-sid prefix ref)))

(defn- instrument-step [trace-sid factory step-sp cancel-p]
  (let [proc-ctx {:pubsub step-sp :step-id trace-sid :cancel cancel-p}
        step-fn  (factory proc-ctx)]
    (wrap-proc trace-sid step-sp step-fn)))

(declare instrument-flow)

(defn- inline-subflow
  [sid subflow outer-sp cancel-p]
  (let [inner-sp      (sp-extend outer-sp [:flow (name sid)])
        inner-inst    (instrument-flow subflow inner-sp cancel-p)
        renamed-procs (into {}
                            (for [[k v] (:procs inner-inst)]
                              [(prefix-sid sid k) v]))
        renamed-conns (mapv (fn [[from to]]
                              [(prefix-endpoint sid from)
                               (prefix-endpoint sid to)])
                            (:conns inner-inst))
        in-ref        (prefix-ref sid (:in inner-inst))
        out-ref       (prefix-ref sid (or (:out inner-inst) (:in inner-inst)))]
    {:procs renamed-procs :conns renamed-conns :in in-ref :out out-ref}))

(defn- resolve-endpoint [aliases which [sid port]]
  (if-let [a (get aliases sid)]
    (let [target (get a which)]
      (if (vector? target) target [target port]))
    [sid port]))

(defn- resolve-flow-ref [ref aliases which]
  (let [sid (if (vector? ref) (first ref) ref)]
    (if-let [a (get aliases sid)]
      (get a which)
      ref)))

(defn- instrument-flow [step outer-sp cancel-p]
  (let [{:keys [procs inner-conns aliases]}
        (reduce (fn [acc [sid p]]
                  (if (subflow? p)
                    (let [{:keys [procs conns in out]}
                          (inline-subflow sid p outer-sp cancel-p)]
                      (-> acc
                          (update :procs clojure.core/merge procs)
                          (update :inner-conns into conns)
                          (assoc-in [:aliases sid] {:in in :out out})))
                    (let [step-sp (sp-extend outer-sp [:step sid])
                          wrapped (instrument-step sid p step-sp cancel-p)]
                      (assoc-in acc [:procs sid] wrapped))))
                {:procs {} :inner-conns [] :aliases {}}
                (:procs step))
        resolved-conns (mapv (fn [[from to]]
                               [(resolve-endpoint aliases :out from)
                                (resolve-endpoint aliases :in to)])
                             (:conns step))
        in-resolved  (when-let [r (:in step)]  (resolve-flow-ref r aliases :in))
        out-resolved (when-let [r (:out step)] (resolve-flow-ref r aliases :out))]
    (cond-> (assoc step
                   :procs procs
                   :conns (into resolved-conns inner-conns))
      (:in step)  (assoc :in  in-resolved)
      (:out step) (assoc :out out-resolved))))

(defn- build-graph [step]
  (flow/create-flow
   {:procs (into {} (map (fn [[sid pfn]] [sid {:proc (flow/process pfn)}])) (:procs step))
    :conns (:conns step)}))

(defn start!
  "Instantiate a step and start it running. Returns a handle."
  ([step] (start! step {}))
  ([step opts]
   (let [fid          (or (:flow-id opts) (str (random-uuid)))
         raw-ps       (or (:pubsub opts) (pubsub/make))
         subscribers  (:subscribers opts {})
         outer-sp     (scoped-pubsub raw-ps [[:flow fid]])
         cancel-p     (promise)
         instrumented (instrument-flow step outer-sp cancel-p)
         port-index   (into {}
                            (map (fn [[sid pfn]]
                                   (let [p (pfn)]
                                     [sid {:ins  (set (keys (:ins  p)))
                                           :outs (set (keys (:outs p)))}])))
                            (:procs instrumented))
         scope        [[:flow fid]]
         events       (atom [])
         counters     (atom {:sent 0 :recv 0 :completed 0})
         quiescent-p  (atom (promise))
         main-sub     (pubsub/sub raw-ps (scope->glob scope)
                                  (fn [_ ev _]
                                    (swap! events conj ev)
                                    (let [c' (swap! counters update-counters ev)]
                                      (when (balanced? c')
                                        (deliver @quiescent-p :quiescent)))))
         user-unsubs  (mapv (fn [[pat h]] (pubsub/sub raw-ps pat h)) subscribers)
         g            (build-graph instrumented)
         {:keys [error-chan]} (flow/start g)
         err-p        (promise)]
     (pubsub/pub raw-ps (run-subject-for scope :run-started)
                 {:kind :run-started :flow-path [fid] :scope scope :at (now)})
     (flow/resume g)
     (a/thread (when-let [ex (a/<!! error-chan)] (deliver err-p ex)))
     {::step        instrumented
      ::graph       g
      ::pubsub      raw-ps
      ::scope       scope
      ::fid         fid
      ::cancel      cancel-p
      ::events      events
      ::counters    counters
      ::quiescent-p quiescent-p
      ::main-sub    main-sub
      ::user-unsubs user-unsubs
      ::err-p       err-p
      ::port-index  port-index})))

(defn inject!
  "Seed a message into the running step. Returns the handle."
  [handle {:keys [in port] :as opts}]
  (let [{::keys [step graph pubsub scope fid counters quiescent-p port-index]} handle
        ref                 (or in (:in step))
        [flow-in flow-port] (if (vector? ref) ref [ref :in])
        port                (or port flow-port)
        step-ports          (get port-index flow-in)
        _                   (when-not step-ports
                              (throw (ex-info
                                      (str "inject!: unknown step " flow-in
                                           " (known: " (sort (keys port-index)) ")")
                                      {:step flow-in :known (set (keys port-index))})))
        _                   (when-not (contains? (:ins step-ports) port)
                              (throw (ex-info
                                      (str "inject!: step " flow-in
                                           " does not declare input port " port
                                           " (declared: " (:ins step-ports) ")")
                                      {:step flow-in :port port :declared (:ins step-ports)})))
        has-data?           (contains? opts :data)
        has-tokens?         (contains? opts :tokens)
        seed                (cond
                              has-data?
                              (cond-> (new-msg (:data opts))
                                has-tokens? (assoc :tokens (:tokens opts)))

                              has-tokens?
                              {:msg-id (random-uuid) :data-id (random-uuid)
                               :tokens (:tokens opts) :parent-msg-ids []}

                              :else
                              (new-done))
        msg-kind            (cond has-data? :data has-tokens? :signal :else :done)]
    (swap! quiescent-p (fn [p] (if (realized? p) (promise) p)))
    (swap! counters update :sent inc)
    (pubsub/pub pubsub (run-subject-for scope :seed)
                (cond-> {:kind :seed :msg-kind msg-kind
                         :flow-path [fid] :scope scope
                         :msg-id (:msg-id seed)
                         :in flow-in :port port :at (now)}
                  has-data?   (assoc :data-id (:data-id seed))
                  has-tokens? (assoc :tokens  (:tokens seed))))
    @(flow/inject graph [flow-in port] [seed])
    handle))

(defn counters
  "Current counter snapshot {:sent :recv :completed}."
  [handle]
  @(::counters handle))

(defn events
  "Snapshot of events collected so far."
  [handle]
  @(::events handle))

(defn quiescent?
  "True iff counters balance and at least one message has been injected."
  [handle]
  (balanced? (counters handle)))

(defn await-quiescent!
  "Block until quiescence or error."
  ([handle] (await-quiescent! handle nil))
  ([handle timeout-ms]
   (let [{::keys [quiescent-p err-p]} handle
         deadline (when timeout-ms (+ (System/currentTimeMillis) timeout-ms))]
     (loop []
       (cond
         (realized? err-p)
         [:failed @err-p]

         (and deadline (>= (System/currentTimeMillis) deadline))
         :timeout

         :else
         (let [current @quiescent-p
               v       (deref current 10 ::pending)]
           (if (= ::pending v) (recur) v)))))))

(defn stop!
  "Tear down the graph."
  [handle]
  (let [{::keys [graph main-sub user-unsubs cancel err-p events counters]} handle]
    (when-not (realized? cancel) (deliver cancel :stopped))
    (flow/stop graph)
    (main-sub)
    (doseq [u user-unsubs] (u))
    (let [err (when (realized? err-p) @err-p)]
      {:state    (if err :failed :completed)
       :events   @events
       :counters @counters
       :error    err})))

(defn run!
  "Convenience: start, inject one message, wait for quiescence, stop."
  [step opts]
  (let [handle (start! step (select-keys opts [:pubsub :flow-id :subscribers]))]
    (inject! handle (select-keys opts [:in :port :data]))
    (let [signal (await-quiescent! handle)]
      (-> (stop! handle)
          (assoc :state (if (= :quiescent signal) :completed :failed))
          (cond-> (vector? signal) (assoc :error (second signal)))))))

(defn- collector-step
  "Terminal step that appends `{:msg-id ... :data ...}` to `a` for every
   data message it receives. Internal to `run-seq`."
  [id a]
  (proc id
        (handler-factory
         {:outs {}}
         (fn [ctx s d]
           (swap! a conj {:msg-id (:msg-id (:msg ctx)) :data d})
           [s []]))))

(defn- parent-index
  "Build `{msg-id #{parent-msg-id ...}}` from an event log, using only
   events that carry both fields."
  [events]
  (reduce (fn [acc ev]
            (let [mid     (:msg-id ev)
                  parents (:parent-msg-ids ev)]
              (if (and mid parents (#{:split :merge :send-out} (:kind ev)))
                (update acc mid (fnil into #{}) parents)
                acc)))
          {} events))

(defn- ancestors-in
  "BFS backward from `msg-id` via `pidx`; return the subset of `targets`
   reached through the ancestry."
  [pidx targets msg-id]
  (loop [frontier #{msg-id} visited #{} found #{}]
    (if (empty? frontier)
      found
      (let [hits      (set/intersection frontier targets)
            visited'  (set/union visited frontier)
            parents   (reduce set/union #{} (map pidx frontier))
            frontier' (set/difference parents visited')]
        (recur frontier' visited' (set/union found hits))))))

(defn run-seq
  "Run `step` against each input in `coll`. Returns a map like `run!`
   plus `:outputs` — a vector aligned with `coll`; each element is the
   vector of data values whose message ancestry traces back to that
   input. An output that traces to multiple inputs (cross-input merge)
   appears under every matching index.

   An internal collector is appended at the step's `:out` boundary, so
   the caller's step should NOT already include its own sink."
  ([step coll] (run-seq step coll {}))
  ([step coll opts]
   (if (empty? coll)
     {:state :completed :outputs [] :events [] :counters {:sent 0 :recv 0 :completed 0}}
     (let [collected (atom [])
           wf        (serial step (collector-step ::collector collected))
           handle    (start! wf (select-keys opts [:pubsub :flow-id :subscribers]))]
       (doseq [d coll] (inject! handle {:data d}))
       (let [signal    (await-quiescent! handle)
             result    (-> (stop! handle)
                           (assoc :state (if (= :quiescent signal) :completed :failed))
                           (cond-> (vector? signal) (assoc :error (second signal))))
             events    (:events result)
             seed-ids  (mapv :msg-id (filter #(= :seed (:kind %)) events))
             seed-set  (set seed-ids)
             seed->idx (zipmap seed-ids (range))
             pidx      (parent-index events)
             outputs   (reduce (fn [acc {:keys [msg-id data]}]
                                 (reduce (fn [a s] (update a (seed->idx s) conj data))
                                         acc
                                         (ancestors-in pidx seed-set msg-id)))
                               (vec (repeat (count coll) []))
                               @collected)]
         (assoc result :outputs outputs))))))
